package br.com.kopp.sistrak.skepi.servicos.usuario;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    long countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    Usuario selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByPrimaryKey(Usuario record);
}