package br.com.kopp.sistrak.base.servicos.usuario;

import java.math.BigDecimal;

class Usuario {

    private Integer id;
    private String nome;
    private String email;
    private String login;
    private String senha;
    private BigDecimal saldo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.id
     *
     * @return the value of public.usuario.id
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.id
     *
     * @param id the value for public.usuario.id
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.nome
     *
     * @return the value of public.usuario.nome
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.nome
     *
     * @param nome the value for public.usuario.nome
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setNome(String nome) {
        this.nome = nome == null ? null : nome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.email
     *
     * @return the value of public.usuario.email
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.email
     *
     * @param email the value for public.usuario.email
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.login
     *
     * @return the value of public.usuario.login
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.login
     *
     * @param login the value for public.usuario.login
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.senha
     *
     * @return the value of public.usuario.senha
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public String getSenha() {
        return senha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.senha
     *
     * @param senha the value for public.usuario.senha
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setSenha(String senha) {
        this.senha = senha == null ? null : senha.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.saldo
     *
     * @return the value of public.usuario.saldo
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public BigDecimal getSaldo() {
        return saldo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.saldo
     *
     * @param saldo the value for public.usuario.saldo
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
}