package br.com.kopp.sistrak.base.servicos.departamento;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioDepartamentoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    long countByExample(UsuarioDepartamentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int deleteByExample(UsuarioDepartamentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int insert(UsuarioDepartamento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int insertSelective(UsuarioDepartamento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    List<UsuarioDepartamento> selectByExample(UsuarioDepartamentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    UsuarioDepartamento selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByExampleSelective(@Param("record") UsuarioDepartamento record, @Param("example") UsuarioDepartamentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByExample(@Param("record") UsuarioDepartamento record, @Param("example") UsuarioDepartamentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByPrimaryKeySelective(UsuarioDepartamento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_departamento
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByPrimaryKey(UsuarioDepartamento record);
}