package br.com.kopp.sistrak.base.servicos.departamento;

public class UsuarioDepartamento {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario_departamento.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario_departamento.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    private String descricao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario_departamento.id_usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    private Integer idUsuarioOrigem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario_departamento.id
     *
     * @return the value of public.usuario_departamento.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario_departamento.id
     *
     * @param id the value for public.usuario_departamento.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario_departamento.descricao
     *
     * @return the value of public.usuario_departamento.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario_departamento.descricao
     *
     * @param descricao the value for public.usuario_departamento.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public void setDescricao(String descricao) {
        this.descricao = descricao == null ? null : descricao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario_departamento.id_usuario_origem
     *
     * @return the value of public.usuario_departamento.id_usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public Integer getIdUsuarioOrigem() {
        return idUsuarioOrigem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario_departamento.id_usuario_origem
     *
     * @param idUsuarioOrigem the value for public.usuario_departamento.id_usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public void setIdUsuarioOrigem(Integer idUsuarioOrigem) {
        this.idUsuarioOrigem = idUsuarioOrigem;
    }
}