package br.com.kopp.sistrak.skepi.persistence.mybatis.dao;

import br.com.kopp.sistrak.skepi.persistence.mybatis.model.Transacao;
import br.com.kopp.sistrak.skepi.persistence.mybatis.model.TransacaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransacaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    long countByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int deleteByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int insert(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int insertSelective(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    List<Transacao> selectByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    Transacao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByExampleSelective(@Param("record") Transacao record, @Param("example") TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByExample(@Param("record") Transacao record, @Param("example") TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByPrimaryKeySelective(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    int updateByPrimaryKey(Transacao record);
}