package br.com.kopp.sistrak.skepi.persistence.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Transacao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.transacao.id
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.transacao.id_usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.transacao.ts_transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    private Date tsTransacao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.transacao.valor
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    private BigDecimal valor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.transacao.id
     *
     * @return the value of public.transacao.id
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.transacao.id
     *
     * @param id the value for public.transacao.id
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.transacao.id_usuario
     *
     * @return the value of public.transacao.id_usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.transacao.id_usuario
     *
     * @param idUsuario the value for public.transacao.id_usuario
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.transacao.ts_transacao
     *
     * @return the value of public.transacao.ts_transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Date getTsTransacao() {
        return tsTransacao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.transacao.ts_transacao
     *
     * @param tsTransacao the value for public.transacao.ts_transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setTsTransacao(Date tsTransacao) {
        this.tsTransacao = tsTransacao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.transacao.valor
     *
     * @return the value of public.transacao.valor
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public BigDecimal getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.transacao.valor
     *
     * @param valor the value for public.transacao.valor
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
}