package br.com.kopp.sistrak.skepi.persistence.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransacaoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public TransacaoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("id_usuario is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("id_usuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(Integer value) {
            addCriterion("id_usuario =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(Integer value) {
            addCriterion("id_usuario <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(Integer value) {
            addCriterion("id_usuario >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_usuario >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(Integer value) {
            addCriterion("id_usuario <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("id_usuario <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<Integer> values) {
            addCriterion("id_usuario in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<Integer> values) {
            addCriterion("id_usuario not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("id_usuario between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("id_usuario not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoIsNull() {
            addCriterion("ts_transacao is null");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoIsNotNull() {
            addCriterion("ts_transacao is not null");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoEqualTo(Date value) {
            addCriterion("ts_transacao =", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoNotEqualTo(Date value) {
            addCriterion("ts_transacao <>", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoGreaterThan(Date value) {
            addCriterion("ts_transacao >", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoGreaterThanOrEqualTo(Date value) {
            addCriterion("ts_transacao >=", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoLessThan(Date value) {
            addCriterion("ts_transacao <", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoLessThanOrEqualTo(Date value) {
            addCriterion("ts_transacao <=", value, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoIn(List<Date> values) {
            addCriterion("ts_transacao in", values, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoNotIn(List<Date> values) {
            addCriterion("ts_transacao not in", values, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoBetween(Date value1, Date value2) {
            addCriterion("ts_transacao between", value1, value2, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andTsTransacaoNotBetween(Date value1, Date value2) {
            addCriterion("ts_transacao not between", value1, value2, "tsTransacao");
            return (Criteria) this;
        }

        public Criteria andValorIsNull() {
            addCriterion("valor is null");
            return (Criteria) this;
        }

        public Criteria andValorIsNotNull() {
            addCriterion("valor is not null");
            return (Criteria) this;
        }

        public Criteria andValorEqualTo(BigDecimal value) {
            addCriterion("valor =", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotEqualTo(BigDecimal value) {
            addCriterion("valor <>", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThan(BigDecimal value) {
            addCriterion("valor >", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("valor >=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThan(BigDecimal value) {
            addCriterion("valor <", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("valor <=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorIn(List<BigDecimal> values) {
            addCriterion("valor in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotIn(List<BigDecimal> values) {
            addCriterion("valor not in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("valor between", value1, value2, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("valor not between", value1, value2, "valor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.transacao
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 16 15:12:08 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.transacao
     *
     * @mbg.generated Fri Dec 16 15:12:08 BRST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}