package br.com.kopp.sistrak.skepi.persistence.mybatis.model;

public class UsuarioOrigem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario_origem.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario_origem.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    private String descricao;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario_origem.id
     *
     * @return the value of public.usuario_origem.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario_origem.id
     *
     * @param id the value for public.usuario_origem.id
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario_origem.descricao
     *
     * @return the value of public.usuario_origem.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario_origem.descricao
     *
     * @param descricao the value for public.usuario_origem.descricao
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    public void setDescricao(String descricao) {
        this.descricao = descricao == null ? null : descricao.trim();
    }
}