package br.com.kopp.sistrak.base.servicos.origem;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioOrigemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    long countByExample(UsuarioOrigemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int deleteByExample(UsuarioOrigemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int insert(UsuarioOrigem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int insertSelective(UsuarioOrigem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    List<UsuarioOrigem> selectByExample(UsuarioOrigemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    UsuarioOrigem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByExampleSelective(@Param("record") UsuarioOrigem record, @Param("example") UsuarioOrigemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByExample(@Param("record") UsuarioOrigem record, @Param("example") UsuarioOrigemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByPrimaryKeySelective(UsuarioOrigem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario_origem
     *
     * @mbg.generated Thu Jan 19 11:06:58 BRST 2017
     */
    int updateByPrimaryKey(UsuarioOrigem record);
}